// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCldK9yTT5ieHRWVymhYMaGGiM80o-BjA8',
    appId: '1:823898404946:web:c08a2482f593c6eebc078b',
    messagingSenderId: '823898404946',
    projectId: 'birthregistration-b7691',
    authDomain: 'birthregistration-b7691.firebaseapp.com',
    storageBucket: 'birthregistration-b7691.appspot.com',
    measurementId: 'G-2BS41JBRRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfzt2-lysv1E1DSctf5g3UwbARva11wzA',
    appId: '1:823898404946:android:d9b0125fb8deac76bc078b',
    messagingSenderId: '823898404946',
    projectId: 'birthregistration-b7691',
    storageBucket: 'birthregistration-b7691.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUlKZIdUtbQUIKq3OLY-olspSQAnUXV30',
    appId: '1:823898404946:ios:c75c152871dfd35bbc078b',
    messagingSenderId: '823898404946',
    projectId: 'birthregistration-b7691',
    storageBucket: 'birthregistration-b7691.appspot.com',
    iosClientId:
        '823898404946-kqrbjclfagvmv9i81g893073d5mnkpta.apps.googleusercontent.com',
    iosBundleId: 'com.example.birthregistration',
  );
}
